# This is a basic workflow to help you get started with Actions

name: passing job values

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  pass_in_one_job:
    runs-on: ubuntu-latest
    steps:
      - name: Set color
        id: color-selector
        run: echo "COLOR=RED" >> "$GITHUB_OUTPUT"
      - name: Get color
        run: echo "The selected color is ${{ steps.color-selector.outputs.COLOR }}"
        
  producer:
    runs-on: ubuntu-latest
    outputs:
      messageOutput: ${{ steps.sentence_maker.outputs.message }}
    steps:
      - name: Make a sentence
        id: sentence_maker
        run: |
            echo "message=jakisMessage" >> "$GITHUB_OUTPUT"

  consumer:
    runs-on: ubuntu-latest
    needs: [producer]
    steps:
      - name: Print the message
        run: echo "${{ needs.producer.outputs.messageOutput }}"

  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > wynik.txt
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: Wynik
          path: wynik.txt

  # job_2:
  #   name: Multiply by 9
  #   needs: job_1
  #   runs-on: windows-latest
  #   steps:
  #     - shell: bash
  #       run: |
  #         value=`cat NAZWA_PLIKU_Z_ARTEFAKTU`
  #         echo $(expr $value \* 9) 
